// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingPractice.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int GuestId { get; set; }

    public int DiningTableId { get; set; }

    public int People { get; set; }

    public int BookingStatus { get; set; }

    public DateTime BookingTime { get; set; }

    public DateTime UpdateTime { get; set; }

    public DateTime CreateTime { get; set; }

    public string Note { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual DiningTable DiningTable { get; set; }

    public virtual Guest Guest { get; set; }
}