// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingPractice.Models;

public partial class DiningTable
{
    public int DiningTableId { get; set; }

    public string TableName { get; set; }

    public int Capacity { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}